version: "3"
services:
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl -4 icanhazip.com"
    depends_on: 
      - vpn
  bombardier:
    image: alpine/bombardier
    command: "-c 1000 -d 3600s -l ${B_TARGET}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  vpn:
    image: polkaned/expressvpn
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - SERVER=by
      - ACTIVATION_CODE=${VPN_CODE}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 300
    command: /bin/bash