version: "3"
services:
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl -4 icanhazip.com"
  bombardier:
    image: alpine/bombardier
    command: "$B_Command"
    network_mode: "service:vpn"
  vpn:
    image: polkaned/expressvpn
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - ACTIVATION_CODE=$vpn_code
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 300
    entrypoint: /bin/bash