FROM nitupkcuf/ddos-ripper:latest
RUN apt update && apt install -y git
RUN rm -rf /app && cd / && git clone https://github.com/Umbriferous/DDoS-Ripper app
WORKDIR /app
COPY ./docker-entrypoint.sh /app/docker-entrypoint.sh
ENTRYPOINT ["/app/docker-entrypoint.sh"]